FROM golang:1.26-trixie AS builder
COPY / /work
WORKDIR /work
RUN apt-get update \
 && apt-get install --yes libsystemd-dev \
 && make client

FROM gcr.io/distroless/base-debian13
COPY --from=builder /work/bin/client /client
CMD ["/client"]
