// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/droptailer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Droptailer_Push_FullMethodName = "/proto.Droptailer/Push"
)

// DroptailerClient is the client API for Droptailer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DroptailerClient interface {
	Push(ctx context.Context, in *Drop, opts ...grpc.CallOption) (*Void, error)
}

type droptailerClient struct {
	cc grpc.ClientConnInterface
}

func NewDroptailerClient(cc grpc.ClientConnInterface) DroptailerClient {
	return &droptailerClient{cc}
}

func (c *droptailerClient) Push(ctx context.Context, in *Drop, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, Droptailer_Push_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DroptailerServer is the server API for Droptailer service.
// All implementations should embed UnimplementedDroptailerServer
// for forward compatibility
type DroptailerServer interface {
	Push(context.Context, *Drop) (*Void, error)
}

// UnimplementedDroptailerServer should be embedded to have forward compatible implementations.
type UnimplementedDroptailerServer struct {
}

func (UnimplementedDroptailerServer) Push(context.Context, *Drop) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}

// UnsafeDroptailerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DroptailerServer will
// result in compilation errors.
type UnsafeDroptailerServer interface {
	mustEmbedUnimplementedDroptailerServer()
}

func RegisterDroptailerServer(s grpc.ServiceRegistrar, srv DroptailerServer) {
	s.RegisterService(&Droptailer_ServiceDesc, srv)
}

func _Droptailer_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Drop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroptailerServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Droptailer_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroptailerServer).Push(ctx, req.(*Drop))
	}
	return interceptor(ctx, in, info, handler)
}

// Droptailer_ServiceDesc is the grpc.ServiceDesc for Droptailer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Droptailer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Droptailer",
	HandlerType: (*DroptailerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _Droptailer_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/droptailer.proto",
}
