// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/droptailer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Drop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drop) Reset() {
	*x = Drop{}
	mi := &file_proto_droptailer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drop) ProtoMessage() {}

func (x *Drop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_droptailer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drop.ProtoReflect.Descriptor instead.
func (*Drop) Descriptor() ([]byte, []int) {
	return file_proto_droptailer_proto_rawDescGZIP(), []int{0}
}

func (x *Drop) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Drop) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_proto_droptailer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_proto_droptailer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_proto_droptailer_proto_rawDescGZIP(), []int{1}
}

var File_proto_droptailer_proto protoreflect.FileDescriptor

const file_proto_droptailer_proto_rawDesc = "" +
	"\n" +
	"\x16proto/droptailer.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x01\n" +
	"\x04Drop\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12/\n" +
	"\x06fields\x18\x02 \x03(\v2\x17.proto.Drop.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x06\n" +
	"\x04Void20\n" +
	"\n" +
	"Droptailer\x12\"\n" +
	"\x04Push\x12\v.proto.Drop\x1a\v.proto.Void\"\x00B}\n" +
	"\tcom.protoB\x0fDroptailerProtoP\x01Z+github.com/metal-stack/droptailer/api/proto\xa2\x02\x03PXX\xaa\x02\x05Proto\xca\x02\x05Proto\xe2\x02\x11Proto\\GPBMetadata\xea\x02\x05Protob\x06proto3"

var (
	file_proto_droptailer_proto_rawDescOnce sync.Once
	file_proto_droptailer_proto_rawDescData []byte
)

func file_proto_droptailer_proto_rawDescGZIP() []byte {
	file_proto_droptailer_proto_rawDescOnce.Do(func() {
		file_proto_droptailer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_droptailer_proto_rawDesc), len(file_proto_droptailer_proto_rawDesc)))
	})
	return file_proto_droptailer_proto_rawDescData
}

var file_proto_droptailer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_droptailer_proto_goTypes = []any{
	(*Drop)(nil),                  // 0: proto.Drop
	(*Void)(nil),                  // 1: proto.Void
	nil,                           // 2: proto.Drop.FieldsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_proto_droptailer_proto_depIdxs = []int32{
	3, // 0: proto.Drop.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: proto.Drop.fields:type_name -> proto.Drop.FieldsEntry
	0, // 2: proto.Droptailer.Push:input_type -> proto.Drop
	1, // 3: proto.Droptailer.Push:output_type -> proto.Void
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_droptailer_proto_init() }
func file_proto_droptailer_proto_init() {
	if File_proto_droptailer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_droptailer_proto_rawDesc), len(file_proto_droptailer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_droptailer_proto_goTypes,
		DependencyIndexes: file_proto_droptailer_proto_depIdxs,
		MessageInfos:      file_proto_droptailer_proto_msgTypes,
	}.Build()
	File_proto_droptailer_proto = out.File
	file_proto_droptailer_proto_goTypes = nil
	file_proto_droptailer_proto_depIdxs = nil
}
